spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

# Product Service
spring.cloud.gateway.routes:
  - id: product
    uri: lb://product-service
    predicates:
      - Path=/api/product/**

  # User Service
  - id: user
    uri: lb://product-service
    predicates:
      - Path=/users/**

  # ProductType Service
  - id: productType
    uri: lb://product-service
    predicates:
      - Path=/productType/**

  # Inventory Service
  - id: inventory
    uri: lb://product-service
    predicates:
      - Path=/inventory/**

  # Cart Service
  - id: cart
    uri: lb://product-service
    predicates:
      - Path=/cart/**

  # Order Service
  - id: order
    uri: lb://order-service
    predicates:
      - Path=/order/**
